<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query\Expr;
/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository {

    public function getAuthoredPosts() 
    {
        
        $qb = $this->createQueryBuilder('p')
            ->select()
            ->leftJoin('AppBundle:Props', 'pr', Expr\Join::WITH , 'pr.post = p.id')
            ->where('pr.author IS NOT NULL')
        ;
        
        return $qb->getQuery()
            ->getResult();
    }

}
