<?php

namespace AppBundle\Repository;

/**
 * PropsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropsRepository extends \Doctrine\ORM\EntityRepository
{
}
